### ISSUE TITLE
C# code returns "Invalid API Key"

### ISSUE THREAD

**Issue by uaqeel** [BitMEX/api-connectors#10]
The C# code returns a HTTPError, "Invalid API Key".

**Comment by STRML** [comment]
Authentication is not implemented on those adapters. They are autogenerated by Swagger-codegen and cannot handle our authentication scheme.

**Comment by uaqeel** [comment]
Then what use are the Swagger adapters? I can use the C# authentication example here:

https://github.com/BitMEX/api-connectors/blob/master/official-http/csharp/BitMEXAPI.cs

But how do I combine it with the Swagger code, eg QuoteApi?

**Comment by STRML** [comment]
They do everything but authentication, because a bespoke authentication scheme like the one used for BitMEX API Keys cannot be specified in Swagger JSON.

The C# implementation (and other codegen implementations) implement all models and apis, which is a very significant chunk of code.

Integrating with the Swagger code is dependent on the individual language. See the source for more details. I am not familiar with the exact structure of each one.

**Comment by uaqeel** [comment]
Your bespoke authentication scheme requires a signature of the request you are making -- if I have to hand-craft the request in order to generate this signature, the Swagger code is completely redundant.

This is completely unusable without a working reference implementation. Can you please provide a working example?

**Comment by STRML** [comment]
This is free code and we supply it as a starting point, but we do not make any guarantees that it will cover your use case, nor do we agree to support it. Only adapters in the `official-` directory are supported by BitMEX.

Use the projects in `clients/` as a starting point, but it is not likely they will work without modification for anything beyond basic unauthenticated use.

**Comment by uaqeel** [comment]
Fine, but understand that your API is unusable without either hand-crafting the client or wading through your Swagger adapters and modifying the code for each endpoint that requires authorisation.

**Comment by autemox** [comment]
No one can get past authorization in C#.  This isn't a "use case".  It's basic function.

**Comment by apobekiaris** [comment]
these adapters can save us a tone of work, we just need the missing authentication part pleae

**Comment by STRML** [comment]
Authentication is implemented in https://github.com/BitMEX/api-connectors/blob/master/official-http/csharp/BitMEXAPI.cs#L87. It should be relatively simple to port that into the Swagger connector.

**Comment by uaqeel** [comment]
That's 3 people who have asked for help and been refused anything other than recycled shitcode. Given Bitmex is a marketplace that relies on high levels of participation and that you're the genius who chose to use a "bespoke authentication scheme", I think it's safe to say you are a terrible CTO. Have fun animating your website, I'm done with Bitmex.

**Comment by STRML** [comment]
I deleted two abusive comments from a person who chose to abuse myself and employees of BitMEX rather than read the documentation.

We understand that this authentication scheme is a pain to deal with, although it is common and the de-facto standard across Bitcoin exchanges. We intend to introduce a simpler token-based scheme in the near future.
