### ISSUE TITLE
API key usage causing Handshake error 400

### ISSUE THREAD

**Issue by scoshil** [BitMEX/api-connectors#162]
Hi,

I was doing some testing with the delta-server (authenticated) while simultaneously connected to an authenticated python websocket instance on a different IP. 

Initially I didn't notice any issues but the next time I restarted the python websocket I started getting handshake status 400 errors when attempting to connect. 

Now (about 2 hours later) I can still use the original API key for REST queries but for websocket I still get the handshake error and have to switch to a different API key to restore functionality. Note that I have been using the python websocket without any troubles for at least a week before this.

I have a few theories but would prefer not to get banned testing them out:

1. Bitmex doesn't allow the same API key to be connected to multiple websockets at once
2. Bitmex doesn't allow the same API key to be connected from more than 1 IP at once
3. Somehow the nonce of the delta-server is incompatible with the python websocket implementation (e.g. something like using ms instead of seconds or something like that...but only for websocket not for REST??).

Can anyone confirm/reject either of the above or suggest another explanation for the cause?

**Comment by ryanfox** [comment]
With older versions of BitMEXs' clients, signed requests to BitMEX could use a nonce value or an expiration scheme [outlined here.](https://testnet.bitmex.com/app/wsAPI#Authentication)
There is more information on the `api-expires` header here: https://testnet.bitmex.com/app/apiKeysUsage#Authenticating-with-an-API-Key

There were issues with the nonce scheme, cf. this note from the above doc:
> Note: Previous versions of this document descripted an api-nonce value, which is a value that should increase between the bounds of 0 and 2^53. This scheme, while still supported, has significant problems with multithreaded clients and should not be used. Do not use it for new applications.

It seems likely that one of your clients set a conflicting nonce, and froze out the other one. As you mentioned, you can work around this by generating a new API key, or (since the default nonce scheme is time-based) wait for the nonce to cycle by. This should be fixed with clients that exclusively use the `api-expires` method. The sample market maker [has an example.](https://github.com/BitMEX/sample-market-maker/blob/master/test/websocket-apikey-auth-test.py)

In general, it's a good practice to have separate API keys for separate applications. This prevents issues like the one you outlined as well as keep applications separate from each other.

**Comment by scoshil** [comment]
thanks for the explanation. Solution seems simple enough!
