### ISSUE TITLE
/quote api returning 403 error

### ISSUE THREAD

**Issue by 1212129** [BitMEX/api-connectors#196]
All API calls to `/quote` return 403, even if you call it directly from the Bitmex API explorer. https://www.bitmex.com/api/explorer/#/Quote  

This bug filing is related to https://github.com/BitMEX/api-connectors/issues/191 which does not seem to be resolved

**Comment by chillz561** [comment]
same problem

**Comment by jbb100** [comment]
me too...

**Comment by cxf739** [comment]
me too ...
2018-08-28 10:40:00,971 - bitmex_websocket - ERROR - Error : Handshake status 403

**Comment by Yackpott** [comment]
Same issue, someone solved this issue?

**Comment by pigslayer12** [comment]
great to see bitmex gives a shit about its API

thought I was going crazy with this error but glad its not just me

**Comment by STRML** [comment]
We will reopen the quote endpoint soon, as we complete a major refactor of our historical query services.

**Comment by beeflowers287** [comment]
> great to see bitmex gives a shit about its API
> 
> thought I was going crazy with this error but glad its not just me

> as workaround, i am using OrderBook/L2

The #BitMEX API is fragmented at best, verging on broken. You can barely get a public price quote (they turned off that endpoint sometime in 2018) so I wanted to share an all in one I've hacked together from their api over the past 6 months for CT and my sanity:

1/ Price
Work around to get the current price is using another endpoint. orderBook/L2 python:

```
import requests, json
response = requests.get("https://www.bitmex.com/api/v1/orderBook/L2?symbol=eth&depth=1 …").json()
ether_bid_price = response[1]['price']
```

2/ Everything else
Digging thru the open Issues of the bitmex github repo this is the best resource I found to help you place/ammend/cancel orders without downloading their sorry excuse sample market maker bot: https://github.com/mazmex7/BitMEX-API-python … 
Thank you @mazmex7

**Comment by bitRomney** [comment]
> as workaround, i am using OrderBook/L2

Using contributions from others who came before me with questions, I've hacked together a complete workaround guide over the past 6 months to allow Python2.x support and to avoid common errors digging thru the many, many open(and carelessly closed) issues in the repo BitMEX/api-connectors. This is an aggregation of useful resources I found to use to the api-connectors without bravado errors and import errors and with Python2.x support:

1 @mazmex7 has developed a nice workaround to support Python2.x. This code is fixed to use in Python 2.x and 3.x. Download here:
https://github.com/mazmex7/BitMEX-API-python
Another common error is 
```
ImportError: No module named parse.
```
His code fixes the ImportError using a try catch in line 3 of the bitmex.py file
Thank you @mazmex7

2 Some may still see this error 
```
/Library/Python/2.7/site-packages/swagger_spec_validator/validator20.py:56: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information.
  warnings.warn(swagger_validation_warning)
```
You can comment out the line 56 of validator20.py where it prints the error because the request is already successful

3 Getting a simple Price Quote
Work around to get the current price is using another endpoint. orderBook/L2 python:

```
import requests, json
response = requests.get("https://www.bitmex.com/api/v1/orderBook/L2?symbol=eth&depth=1 …").json()
ether_bid_price = response[1]['price']
```

**Comment by umatomba** [comment]
> We will reopen the quote endpoint soon, as we complete a major refactor of our historical query services.

why you close not resolved issues....
