### ISSUE TITLE
Websocket "order" stream returns 0 open orders while there are plenty

### ISSUE THREAD

**Issue by anedosugov** [BitMEX/api-connectors#259]
~50% of the time the orders websocket continues to return [] while orders are being opened

**Comment by Madward** [comment]
If you're using the node.js websocket api, the issue has been mentioned a few times here.

The problem occurs because of a bug that only happens if you don't have any orders opened at the time. An easy fix is to open an order with a price far from market, start listening to the "orders" websocket, and cancel the order.
You could also try one of the fixes proposed by community members in related issues.

#210 
#203 
#166

**Comment by ecooperman** [comment]
I was able to fix it as I'm using both the REST and Websocket APIs but first checking whether I have orders, and if there are none, don't open the stream until I place the first order through the REST API...but not everyone is using both APIs I'm sure so this will likely only work for a subset of people.

There is a pull request open for this that I haven't been able to test (I'm fairly new to Node and I haven't taken the time to pull down the code from the branch (patch-2 I believe) to test it, but it would be nice if others could verify the fix and get that thing merged.  Who can we reach out to about merging PRs?

**Comment by STRML** [comment]
Fixed in a6a2236325edbe178e70ebc5164cd3eef977bfb0
