### ISSUE TITLE
The program stucked after 'Connected to WS.'

### ISSUE THREAD

**Issue by zlwolf236** [BitMEX/api-connectors#28]
Hi, I used exactly the same main trying to connect to the websocket using endpoint="wss://www.bitmex.com/realtime"

It went through Authentication and successfully connected to WebSocket; however, the program stucked at

if api_key:
    self.__wait_for_account()

part. Can anyone tell me what I did wrong here? I tried to copy the whole link to a browser and it says "Upgrade Required"

Please help, thank you very much

**Comment by lechiffreqc** [comment]
Same problem here. Code was working well, then now got stuck here: 
    def __wait_for_account(self):
        '''On subscribe, this data will come down. Wait for it.'''
        # Wait for the keys to show up from the ws
        while not {'margin', 'position', 'order', 'orderBook25'} <= set(self.data):

**Comment by lechiffreqc** [comment]
I don't know if it will help, but I removed the parameter 

'orderBook25' from 
def __wait_for_account(self): in 
bitmex_websocket.py

I don't know if I am right, but according to available data from 
https://www.bitmex.com/app/wsAPI#Connecting 
there is not 'orderBook25' subject in authentificated channel. 

Since I have removed this parameter, I am able to login again.

Good luck.

**Comment by STRML** [comment]
Thanks, pushed a fix.
