### ISSUE TITLE
/execution/tradeHistory not giving full history

### ISSUE THREAD

**Issue by pdepip** [BitMEX/api-connectors#280]
When I make requests to  /execution/tradeHistory I am only receiving orders from the past week or so (~28 trades). This was not an issue several days ago, I can confirm the same behavior is happening on the website. This is not an issue on the testnet. Is this intentional?

```
client = bitmex.bitmex(test=False, api_key=key, api_secret=secret)

trades = client.Execution.Execution_getTradeHistory(start=0, count=500, reverse=False).result()[0]
```

**Comment by Madward** [comment]
Same here, but irrelevant to this Github.

This is a global BitMEX issue, as you can see on https://www.bitmex.com/app/tradeHistory. The Python API connector (as well as the other connectors) is accurate on the data it returns, the base data made available by BitMEX is the one that's lacking.

As such, this is a request that should be made to BitMEX directly, maybe via a [support ticket](https://bitmex.freshdesk.com/support/tickets/new).

**Comment by STRML** [comment]
Hi - this was resolved quite a while ago, we apologize for not responding to this ticket. For some time, historical data was limited in public scope (but available via Support request) due to in-progress upgrades in our technology stack for serving those requests. Those were completed some time ago and all data is available.
