### ISSUE TITLE
openingTimestamp is incorrect 

### ISSUE THREAD

**Issue by macd2** [BitMEX/api-connectors#295]
When calling the API OpeningTimestamp is wrong if it represents the opening time of position what i assume?

**Comment by mattou78400** [comment]
Same problem here....
Could you find a solution?

**Comment by bendelo** [comment]
It is the openingTimestamp of the trading session, which rolls every hour. You can use the execution history to get the trade that opened your position.

**Comment by enriquepiatti** [comment]
That sucks, so we need to make another API call to get the opening time of our position??

**Comment by hems** [comment]
> It is the openingTimestamp of the trading session, which rolls every hour. You can use the execution history to get the trade that opened your position.

Let's hypothetically consider a position might contain thousands of trades, for instance on a perpetual market, in order to know the timestamp of the first trade which opened the position then multiple requests would have to be made to the API and then "manually" create associations between the trades and the currently opened position.

It would be easier if the position contains a `createdAtTimestamp` property which isn't updated every time the position is rolled over, then with that timestamp, we could query:

"ALL TRADES where createdAt >= position.createdAtTimestamp"

And fetch only the relevant trades in one call ( paginated if there are too many trades )?
