### ISSUE TITLE
Getting "Nonce is not increasing" error with Node.js WS Lib

### ISSUE THREAD

**Issue by backupManager** [BitMEX/api-connectors#64]
I'm trying to use the WS library to get realtime updates and using the Swagger client to make orders. This is the error I get whenever I try to connect with the WebSocket library (Node.js: https://github.com/BitMEX/api-connectors/tree/master/official-ws/nodejs).

Any help or pointers appreciated.

```sh
WebSocket [ERROR]: Unexpected response from server [400]: {"error":"Nonce is not increasing. This nonce: 1515130196494, last nonce: 1515128183690000"}
WebSocket [INFO]: The WebSocket will terminate. Please manually reconnect.
WebSocket [ERROR]: Closing Websocket

/node_modules/bitmex-realtime-api/lib/createSocket.js:71
    if (!listeners.length) throw new Error('WebSocket closed. Please check errors above.');
Error: WebSocket closed. Please check errors above.
    at WebSocketClient.wsClient.onend (/node_modules/bitmex-realtime-api/lib/createSocket.js:71:34)
    at WebSocket.instance.on (/node_modules/bitmex-realtime-api/lib/ReconnectingSocket.js:41:18)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at IncomingMessage.response.on (/node_modules/bitmex-realtime-api/lib/ReconnectingSocket.js:69:27)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by andersea** [comment]
If you are using the same api key for both rest and websocket, there is a chance this can happen, since api calls can fall out of sync. Try using different keys for the rest interface and the websocket and see if that resolves the issue.

**Comment by ko0f** [comment]
> `{"error":"Nonce is not increasing. This nonce: 1515130196494, last nonce: 1515128183690000"}`

The two nonces have different format, one is in milliseconds and the other in microseconds. You should use the same format on both clients.

**Comment by ryanfox** [comment]
Now the node-swagger and node-ws clients use the same nonce scheme. With a new API key, this shouldn't happen any more.

**Comment by annugaurish** [comment]
I have solved this problem by making changes in **createSocket.js**
Added following code in the createSocket function

wsClient.onreconnect = function() {
         wsClient.url = makeEndpoint(options);
		
	debug('Reconnecting to BitMEX at ', wsClient.url);
};

and in **ReconnectionSocket.js** added the following line in reconnect prototype
   this.onreconnect();

this is to be added before this.open(this.url);

**Changed API keys but it was not solving issue**

**Comment by annugaurish** [comment]
**Changed API keys but it was not solving issue**

**Comment by QuentinFAIDIDE** [comment]
Nonce is increased with each websocket request so you can send something with the javascript socket.send(message, callback) method from time to time to fix this if you're not using the websocket client actively. This was mentioned on another similar issue. if you don't the nonce does not increase and you get the 'nonce not increasing' message from bitmex servers. 
A call from time to time to this send method from the socket member of the _bitmexRealtimeApi2.default class (or even BitmexPlus class cause of inheritance) prevent the 'nonce' message from appearing and throwing the error.
I tried to send REST requests from time to time, and used different new keys for the websocket protocol by editing around the node packages, nothing really fixed the issue until I started sending 'ping' messages through the socket. I might be missing something through.
Anyway, not sure that pinging is a healthy solution to this isssue, especially when Bitmex servers might already have lots of inactive opened sockets they will want to kick out one day, because if someone wants to use REST requests for prices instead of WS when they have no position opened (I do), he can't disconnect the socket with the connector member functions, he has to access its member objects and hack around, it kind of breaks regular OOP encapsulation.  
Bitfinex node API lets you request a reference to a websocket object from their main connector class, maybe this project needs to do the same and encapsulate the socket in another class so users can manipulate and start ws connections by themselves.
