### ISSUE TITLE
Warning: JSON format is not registered with bravado-core!   category=Warning,

### ISSUE THREAD

**Issue by HarryWang0210** [BitMEX/api-connectors#83]
I tried to run the code
`client.Instrument.Instrument_get(filter=json.dumps({'symbol': 'XBTUSD'})).result()`
`client.Order.Order_new(symbol='XBTUSD', orderQty=10, price=8000.0).result()`
but it say
`C:\Users\Harry\Anaconda3\lib\site-packages\bravado_core\spec.py:324: Warning: JSON format is not registered with bravado-core!
  category=Warning,`
`C:\Users\Harry\Anaconda3\lib\site-packages\bravado_core\spec.py:324:Warning: guid format is not registered with bravado-core!
  category=Warning,`
does anyone has this problem too?

I use python and my computer is Windows 10

**Comment by ryanfox** [comment]
Placing orders requires authentication, make sure you create `client` with a valid API key and API secret.

**Comment by HarryWang0210** [comment]
I am sure that my API key is correct because  I can post an order and get instrument  thought it said the formats are not registered with bravado-core.

**Comment by d1Ng0** [comment]
+1

**Comment by ryanfox** [comment]
What version of bravado and bravado-core are installed? I am unable to reproduce this.

**Comment by d1Ng0** [comment]
/usr/local/lib/python3.6/site-packages/bravado_core/spec.py:324: Warning: JSON format is not registered with bravado-core!
  category=Warning,

>>> bravado.version
'9.2.2'

**Comment by HarryWang0210** [comment]
bravado 9.2.2
bravado-core 4.12.1

**Comment by tsoonami** [comment]
+1

**Comment by flecill** [comment]
client = bitmex.bitmex(test=False, api_key ='xxxxxxxxxxxxxxxxxxxxxx', api_secret='xxxxxxxxxxxxxxxxxxx')
res = client.Order.Order_new(symbol='XBTUSD', orderQty=1, price=9000).result()

guid format is not registered with bravado-core!
category=Warning,

Encountered similar issue.
But the order was placed. version is bravado-9.2.2

**Comment by xguo-prestolabs** [comment]
Encountered same problem.

**Comment by xguo-prestolabs** [comment]
I traced the warning and found that it is raised during the serialization of the params. It has no negative side is the value is string. For the filter parameter, the type of the parameter is string, but the format is JSON, so the serializer tries to get the JSON formatter to serialize the data, but failed, because bravado does not know JSON, so the value is returned, which is fine, because string does not need any further preprocessing. But I'm not sure when URL encode is done, probably in later steps.

One way to get rid of this warning is remove format field for the filter parameter in swagger.json.

**Comment by guoxiaoyong** [comment]
I traced the warning and found that it is raised during the serialization of the params. It has no negative side is the value is string. For the filter parameter, the type of the parameter is string, but the format is JSON, so the serializer tries to get the JSON formatter to serialize the data, but failed, because bravado does not know JSON, so the value is returned, which is fine, because string does not need any further processing. But I'm not sure when URL encode is done, probably in later steps.

One way to get rid of this warning is remove format field for the filter parameter in swagger.json.

**Comment by ryanfox** [comment]
Thanks for the feedback - at this point, you may want to catch the exception and do whatever you wish. The request was already successful, so it does not affect the requests sent to the trading engine.

**Comment by mazmex7** [comment]
Hi, I found same problem, and I fixed some lib's code to resolve this personally.
Please feel free to use, if you like 😄 
https://github.com/mazmex7/BitMEX-API-python

**Comment by bitRomney** [comment]
Using contributions from others who came before me with questions, I've hacked together a complete workaround guide over the past 6 months to allow Python2.x support and to avoid common errors digging thru the many, many open(and carelessly closed) issues in the repo BitMEX/api-connectors. This is an aggregation of useful resources I found to use to the api-connectors without bravado errors and import errors and with Python2.x support:

1 @mazmex7 has developed a nice workaround to support Python2.x. This code is fixed to use in Python 2.x and 3.x. Download here:
https://github.com/mazmex7/BitMEX-API-python
Another common error is 
```
ImportError: No module named parse.
```
His code fixes the ImportError using a try catch in line 3 of the bitmex.py file
Thank you @mazmex7

2 Some may still see this error 
```
/Library/Python/2.7/site-packages/swagger_spec_validator/validator20.py:56: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information.
  warnings.warn(swagger_validation_warning)
```
You can comment out the line 56 of validator20.py where it prints the error because the request is already successful

3 Getting a simple Price Quote
Work around to get the current price is using another endpoint. orderBook/L2 python:

```
import requests, json
response = requests.get("https://www.bitmex.com/api/v1/orderBook/L2?symbol=eth&depth=1 …").json()
ether_bid_price = response[1]['price']
```

**Comment by shaneoshea** [comment]
Sending the request with double quotes instead of single quotes solved the issue for me:

`client.Instrument.Instrument_get(filter=json.dumps({"symbol": "XBTUSD"})).result()`

**Comment by Kinzowa** [comment]
> I traced the warning and found that it is raised during the serialization of the params. It has no negative side is the value is string. For the filter parameter, the type of the parameter is string, but the format is JSON, so the serializer tries to get the JSON formatter to serialize the data, but failed, because bravado does not know JSON, so the value is returned, which is fine, because string does not need any further processing. But I'm not sure when URL encode is done, probably in later steps.
> 
> One way to get rid of this warning is remove format field for the filter parameter in swagger.json.

Hi, where is `swagger.json` located?
